apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- configMap.yaml
- service.yaml
- statefulset.yaml
- secret.yaml
- service-account.yaml
namespace: mongodb-repl-system

